export const NODE_LABELS: Record<string, string> = {
  "brent_crude": "Brent Crude",
  "consumer_confidence": "Consumer Confidence",
  "copper": "Copper",
  "dxy_index": "DXY Index",
  "energy_sector": "Energy Sector",
  "eurusd": "EUR/USD",
  "fed_balance_sheet": "Fed Balance Sheet",
  "fed_funds_rate": "Fed Funds Rate",
  "financials_sector": "Financials Sector",
  "gold": "Gold",
  "hy_credit_spread": "HY Credit Spread",
  "ig_credit_spread": "IG Credit Spread",
  "move_index": "MOVE Index",
  "nasdaq": "NASDAQ",
  "natural_gas": "Natural Gas",
  "pce_deflator": "PCE Deflator",
  "russell2000": "Russell 2000",
  "silver": "Silver",
  "skew_index": "SKEW Index",
  "sp500": "S&P 500",
  "tech_sector": "Tech Sector",
  "unemployment_rate": "Unemployment Rate",
  "us_10y_yield": "US 10Y Yield",
  "us_2y_yield": "US 2Y Yield",
  "us_30y_yield": "US 30Y Yield",
  "us_cpi_yoy": "US CPI YoY",
  "us_gdp_growth": "US GDP Growth",
  "us_political_risk": "US Political Risk",
  "usdcny": "USD/CNY",
  "usdjpy": "USD/JPY",
  "vix": "VIX",
  "wage_growth": "Wage Growth",
  "wheat": "Wheat",
  "wti_crude": "WTI Crude Oil",
  "yield_curve_spread": "Yield Curve Spread",
};

export function getNodeLabel(nodeId: string): string {
  return NODE_LABELS[nodeId] || nodeId.replace(/_/g, " ").replace(/\b\w/g, (c) => c.toUpperCase());
}
